[package]
name = "distribute_collect_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.6"
tokio = { version = "1.40.0", features = ["full"] }
serde = "1.0.128"
serde_json = "1.0.128"
dotenvy = "0.15.7"
alloy = { version = "0.2.1", features = ["full"] }
anyhow = "1.0.89"